### ISSUE TITLE
Quill should ensure previous lifecycle actions have occurred

### ISSUE THREAD

**Issue by indexzero** [opsmezzo/quill#13]
In order of priority:

**Start**
1. install
2. configure
3. start

**Restart**
1. install
2. configure
3. restart

**Update**
1. install
2. configure
3. update

**Uninstall**
1. uninstall

**Comment by mmalecki** [comment]
@indexzero should this use history data?

**Comment by indexzero** [comment]
@mmalecki Yes. We could be storing this in the database for the server, might make our lives easier instead of storing ephemeral files.

**Comment by indexzero** [comment]
@mmalecki All of these hierarchies should be run regardless of the command. In other words: **if `action` and not installed, run `install` and `configure` then `action`.** Two notes:
- The exception here of course is `uninstall` which should do nothing if not installed.
- We should add a --strict option which will throw if the system is not already installed and configured.
