### ISSUE TITLE
Uninstall previous system version before installing newer version

### ISSUE THREAD

**Issue by indexzero** [opsmezzo/quill#2]
nt

**Comment by mmalecki** [comment]
@indexzero couple of questions on this one.
- Should it just call `uninstall` script of the system?
- If so, should it care about version of the system it's uninstalling? As in, I'm installing `system@0.0.1` on top of `system@0.0.0` - which `uninstall` script should be called?
- If no, how do we uninstall the system?

**Comment by indexzero** [comment]
- Should it just call `uninstall` script of the system? _Yes_
- If so, should it care about version of the system it's uninstalling? As in, I'm installing `system@0.0.1` on top of `system@0.0.0` - which `uninstall` script should be called? _The uninstall script for the previous version of the system seems like the logical choice_

**Comment by indexzero** [comment]
Fixed in #15
