### ISSUE TITLE
quill <lifecycle> --watch

### ISSUE THREAD

**Issue by indexzero** [opsmezzo/quill#61]
**_Useful for development_**

Long running quill process which listens to the changes feed from composer and auto updates anything installed.

**Comment by indexzero** [comment]
Maybe `quill live`?

**Comment by mmalecki** [comment]
Maybe `quill <lifecycle> --watch`? This'd apply to every lifecycle action, including configuration changes, etc.

**Comment by indexzero** [comment]
@mmalecki That's a good semantic. Indicates what you're waiting for.

**Comment by indexzero** [comment]
Fixed by #72
