### ISSUE TITLE
externalDependencies

### ISSUE THREAD

**Issue by indexzero** [opsmezzo/quill#75]
e.g. 

``` js
{
  "externalDependencies": {
    "npm": {
      "system.json": "1.0.x"
    }
  }
}
```

would `npm install system.json@1.0.x -g` ... probably best managed by some smaller library (maybe called `wtfpkg`) that parses and aggregates package manager information  for common pms:
- yum
- apt
- rpm
- dpkg
- npm
- rubygems
- pip
- nuget
- pear

**Comment by mmalecki** [comment]
I'm implementing this, but with the following syntax:

```
"externalDependencies": {
    "npm": [""system.json@1.0.x"]
}
```

Different systems have different notion of version and different separators, so let's just go with this instead of trying to write an adapter for each package manager.

**Comment by indexzero** [comment]
Sounds like a good solution
